gscam_publisher:
  ros__parameters:
    gscam_config: "v4l2src device=/dev/video0 ! image/jpeg,width=1920,height=1080,framerate=30/1 ! jpegdec ! videoconvert ! tee name=t   t. ! queue ! videoconvert ! video/x-raw,format=RGB ! identity name=ros_branch   t. ! queue ! x264enc tune=zerolatency bitrate=4000 speed-preset=veryfast key-int-max=30 ! video/x-h264,profile=baseline ! h264parse ! flvmux streamable=true ! rtmpsink location=rtmp://media.dyinnovations.com/live/livestream live=1"
    image_encoding: rgb8
    use_gst_timestamps: true